//! The Modbus register map as data.
//!
//! The ADR calls this the contract the future RS-485 "duck" protocol
//! reuses, so the table lives here (one source), the server in granite-fw
//! reads values through [`discrete_inputs`], [`input_registers`],
//! [`holding_registers`] and [`coils`], writes come back as a
//! [`Command`] through [`command_from_holding`] / [`command_from_coil`],
//! and `firmware/docs/modbus_map.md` is generated by
//! [`render_markdown`].
//!
//! Register 14 of the input registers is the map version. Freeze the map
//! by bumping [`MAP_VERSION`] before any external integration.

use alloc::format;
use alloc::string::{String, ToString};
use core::fmt;

use crate::actuator::{ActionKind, ActionResult};
use crate::hal::TEMP_MISSING;
use crate::msg::{Args, Command, CommandKind};
use crate::node::NodeState;
use crate::observed::Observed;
use crate::{DRY_COUNT, NODE_COUNT, NodeId, PROBE_SLOTS, Target};

/// Version of this map, exposed in input register 14.
pub const MAP_VERSION: u16 = 1;

/// Number of discrete inputs.
pub const DISCRETE_COUNT: usize = 14;
/// Number of input registers.
pub const INPUT_COUNT: usize = 15;
/// Number of holding registers.
pub const HOLDING_COUNT: usize = 10;
/// Number of coils.
pub const COIL_COUNT: usize = NODE_COUNT;

/// Holding-register command words.
pub mod cmd_word {
    /// No command / cleared.
    pub const NONE: u16 = 0;
    /// `on`.
    pub const ON: u16 = 1;
    /// `off` (escalates like the MQTT command).
    pub const OFF: u16 = 2;
    /// `force_off`.
    pub const FORCE_OFF: u16 = 3;
    /// `reset`.
    pub const RESET: u16 = 4;
    /// `cycle`.
    pub const CYCLE: u16 = 5;
}

/// Bits of input register 13.
pub mod fault_bits {
    /// Expander readback mismatch or a blown press deadline.
    pub const EXPANDER: u16 = 1 << 0;
    /// The power LEDs could not be read.
    pub const SENSE: u16 = 1 << 1;
    /// A configured probe did not answer.
    pub const PROBE_MISSING: u16 = 1 << 2;
    /// VIN outside the configured window.
    pub const VIN: u16 = 1 << 3;
    /// An OTA image is pending validation.
    pub const OTA_PENDING: u16 = 1 << 4;
    /// A config section fell back to its defaults at boot.
    pub const CONFIG_FALLBACK: u16 = 1 << 5;
    /// The broker is configured but not connected.
    pub const MQTT_DOWN: u16 = 1 << 6;
}

/// What register 9 of the holding registers reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u16)]
pub enum ResultCode {
    /// Nothing has been commanded yet.
    #[default]
    Idle = 0,
    /// The last command finished successfully.
    Ok = 1,
    /// The last command is still running.
    Accepted = 2,
    /// The last command was refused.
    Refused = 3,
    /// The last command failed.
    Failed = 4,
    /// Soft-off is still pending on the node.
    ShutdownPending = 5,
}

impl ResultCode {
    /// Register value.
    pub const fn as_u16(self) -> u16 {
        self as u16
    }

    /// Map an action result onto a code.
    pub const fn of_result(r: &ActionResult) -> Self {
        match r {
            ActionResult::Ok => ResultCode::Ok,
            ActionResult::ShutdownPending => ResultCode::ShutdownPending,
            ActionResult::Refused { .. } => ResultCode::Refused,
            ActionResult::Failed { .. } => ResultCode::Failed,
        }
    }
}

/// Firmware version as the map reports it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct FwVersion {
    /// Major.
    pub major: u8,
    /// Minor.
    pub minor: u8,
}

impl FwVersion {
    /// Packed `major << 8 | minor`.
    pub const fn as_u16(self) -> u16 {
        ((self.major as u16) << 8) | self.minor as u16
    }
}

/// Which table an entry belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegKind {
    /// Function 2, read only, one bit.
    DiscreteInput,
    /// Function 4, read only, 16 bits.
    InputRegister,
    /// Functions 3 / 6 / 16, read and write, 16 bits.
    HoldingRegister,
    /// Functions 1 / 5, read and write, one bit.
    Coil,
}

impl RegKind {
    /// Table name for the documentation.
    pub const fn as_str(self) -> &'static str {
        match self {
            RegKind::DiscreteInput => "Discrete inputs",
            RegKind::InputRegister => "Input registers",
            RegKind::HoldingRegister => "Holding registers",
            RegKind::Coil => "Coils",
        }
    }
}

/// Read / write permission of an entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Access {
    /// Read only.
    R,
    /// Read and write.
    Rw,
}

impl Access {
    /// Documentation string.
    pub const fn as_str(self) -> &'static str {
        match self {
            Access::R => "r",
            Access::Rw => "rw",
        }
    }
}

/// One row of the map.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RegEntry {
    /// Which table.
    pub kind: RegKind,
    /// Address inside that table.
    pub addr: u16,
    /// Short identifier.
    pub name: &'static str,
    /// What it means.
    pub meaning: &'static str,
    /// Unit and scaling.
    pub scale: &'static str,
    /// Permission.
    pub access: Access,
}

const fn di(addr: u16, name: &'static str, meaning: &'static str) -> RegEntry {
    RegEntry {
        kind: RegKind::DiscreteInput,
        addr,
        name,
        meaning,
        scale: "0/1",
        access: Access::R,
    }
}

const fn ir(addr: u16, name: &'static str, meaning: &'static str, scale: &'static str) -> RegEntry {
    RegEntry {
        kind: RegKind::InputRegister,
        addr,
        name,
        meaning,
        scale,
        access: Access::R,
    }
}

const fn hr(addr: u16, name: &'static str, meaning: &'static str, scale: &'static str) -> RegEntry {
    RegEntry {
        kind: RegKind::HoldingRegister,
        addr,
        name,
        meaning,
        scale,
        access: Access::Rw,
    }
}

const fn co(addr: u16, name: &'static str, meaning: &'static str) -> RegEntry {
    RegEntry {
        kind: RegKind::Coil,
        addr,
        name,
        meaning,
        scale: "0/1",
        access: Access::Rw,
    }
}

/// The whole map, in table and address order.
pub const MAP: &[RegEntry] = &[
    di(0, "node1_led", "Node 1 power LED, 1 = on"),
    di(1, "node2_led", "Node 2 power LED, 1 = on"),
    di(2, "node3_led", "Node 3 power LED, 1 = on"),
    di(3, "node4_led", "Node 4 power LED, 1 = on"),
    di(4, "node5_led", "Node 5 power LED, 1 = on"),
    di(5, "node6_led", "Node 6 power LED, 1 = on"),
    di(6, "node7_led", "Node 7 power LED, 1 = on"),
    di(7, "node8_led", "Node 8 power LED, 1 = on"),
    di(8, "dry_in1", "Dry contact 1, 1 = closed"),
    di(9, "dry_in2", "Dry contact 2, 1 = closed"),
    di(10, "dry_in3", "Dry contact 3, 1 = closed"),
    di(11, "dry_in4", "Dry contact 4, 1 = closed"),
    di(12, "link_up", "Ethernet link, 1 = up"),
    di(13, "mqtt_connected", "MQTT session, 1 = connected"),
    ir(
        0,
        "probe1_temp",
        "Probe slot 1 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        1,
        "probe2_temp",
        "Probe slot 2 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        2,
        "probe3_temp",
        "Probe slot 3 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        3,
        "probe4_temp",
        "Probe slot 4 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        4,
        "probe5_temp",
        "Probe slot 5 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        5,
        "probe6_temp",
        "Probe slot 6 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        6,
        "probe7_temp",
        "Probe slot 7 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        7,
        "probe8_temp",
        "Probe slot 8 temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(
        8,
        "board_temp",
        "TMP1075 board temperature",
        "0.01 C, signed, 0x8000 = missing",
    ),
    ir(9, "vin", "Bus voltage", "mV, 0 = never read"),
    ir(10, "uptime_hi", "Seconds since boot, high word", "s"),
    ir(11, "uptime_lo", "Seconds since boot, low word", "s"),
    ir(12, "fw_version", "Firmware version", "major << 8 | minor"),
    ir(13, "fault_flags", "Fault bitmap, see fault_bits", "bitmap"),
    ir(14, "map_version", "Version of this register map", "integer"),
    hr(
        0,
        "node1_cmd",
        "Node 1: write a command word, read the node state",
        "w: 1 on, 2 off, 3 force_off, 4 reset, 5 cycle; r: 0 unknown, 1 off, 2 on, 3 busy",
    ),
    hr(
        1,
        "node2_cmd",
        "Node 2: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        2,
        "node3_cmd",
        "Node 3: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        3,
        "node4_cmd",
        "Node 4: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        4,
        "node5_cmd",
        "Node 5: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        5,
        "node6_cmd",
        "Node 6: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        6,
        "node7_cmd",
        "Node 7: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        7,
        "node8_cmd",
        "Node 8: write a command word, read the node state",
        "see node1_cmd",
    ),
    hr(
        8,
        "on_all",
        "Write 1 to run the staggered on_all",
        "w: 1 trigger; r: 0",
    ),
    hr(
        9,
        "last_result",
        "Result of the last command word",
        "0 idle, 1 ok, 2 accepted, 3 refused, 4 failed, 5 shutdown_pending",
    ),
    co(
        0,
        "node1_power",
        "Node 1: read the state, write 1 = on, 0 = off",
    ),
    co(
        1,
        "node2_power",
        "Node 2: read the state, write 1 = on, 0 = off",
    ),
    co(
        2,
        "node3_power",
        "Node 3: read the state, write 1 = on, 0 = off",
    ),
    co(
        3,
        "node4_power",
        "Node 4: read the state, write 1 = on, 0 = off",
    ),
    co(
        4,
        "node5_power",
        "Node 5: read the state, write 1 = on, 0 = off",
    ),
    co(
        5,
        "node6_power",
        "Node 6: read the state, write 1 = on, 0 = off",
    ),
    co(
        6,
        "node7_power",
        "Node 7: read the state, write 1 = on, 0 = off",
    ),
    co(
        7,
        "node8_power",
        "Node 8: read the state, write 1 = on, 0 = off",
    ),
];

/// Look one entry up.
pub fn entry(kind: RegKind, addr: u16) -> Option<&'static RegEntry> {
    MAP.iter().find(|e| e.kind == kind && e.addr == addr)
}

/// Why a Modbus write could not be turned into a command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MapError {
    /// No such register in this table (Modbus exception 2).
    UnknownRegister {
        /// Which table.
        kind: RegKind,
        /// Which address.
        addr: u16,
    },
    /// The register exists but the value means nothing (exception 3).
    BadValue {
        /// Which address.
        addr: u16,
        /// What was written.
        value: u16,
    },
}

impl fmt::Display for MapError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MapError::UnknownRegister { kind, addr } => {
                write!(f, "no {} at {addr}", kind.as_str())
            }
            MapError::BadValue { addr, value } => {
                write!(f, "value {value} is not valid for register {addr}")
            }
        }
    }
}

/// Discrete inputs, in address order.
pub fn discrete_inputs(o: &Observed) -> [bool; DISCRETE_COUNT] {
    let mut out = [false; DISCRETE_COUNT];
    for (i, bit) in out[..NODE_COUNT].iter_mut().enumerate() {
        *bit = o.node_led((i + 1) as NodeId) == Some(true);
    }
    for (i, bit) in out[NODE_COUNT..NODE_COUNT + DRY_COUNT]
        .iter_mut()
        .enumerate()
    {
        *bit = o.dry((i + 1) as u8) == Some(true);
    }
    out[12] = o.link_up.value;
    out[13] = o.mqtt_connected.value;
    out
}

/// Input registers, in address order.
pub fn input_registers(o: &Observed, fw: FwVersion, faults: u16) -> [u16; INPUT_COUNT] {
    let mut out = [0u16; INPUT_COUNT];
    for (slot, reg) in out[..PROBE_SLOTS].iter_mut().enumerate() {
        let centi = o
            .probe(slot)
            .and_then(|p| p.centi_c)
            .unwrap_or(TEMP_MISSING);
        *reg = centi as u16;
    }
    out[8] = o.board_temp.value.unwrap_or(TEMP_MISSING) as u16;
    out[9] = o.vin_mv.value.unwrap_or(0).min(u16::MAX as u32) as u16;
    out[10] = (o.uptime_s.value >> 16) as u16;
    out[11] = (o.uptime_s.value & 0xffff) as u16;
    out[12] = fw.as_u16();
    out[13] = faults;
    out[14] = MAP_VERSION;
    out
}

/// Holding registers, in address order. The node words read back the node
/// state, the `on_all` trigger reads 0, and register 9 is the result of
/// the last command word.
pub fn holding_registers(o: &Observed, last_result: ResultCode) -> [u16; HOLDING_COUNT] {
    let mut out = [0u16; HOLDING_COUNT];
    for (i, reg) in out[..NODE_COUNT].iter_mut().enumerate() {
        *reg = o.node_state((i + 1) as NodeId).as_modbus();
    }
    out[8] = 0;
    out[9] = last_result.as_u16();
    out
}

/// Coils, in address order: node power mirrors.
pub fn coils(o: &Observed) -> [bool; COIL_COUNT] {
    let mut out = [false; COIL_COUNT];
    for (i, bit) in out.iter_mut().enumerate() {
        *bit = matches!(o.node_state((i + 1) as NodeId), NodeState::On);
    }
    out
}

/// Turn a holding-register write into a command.
///
/// `Ok(None)` means the write is accepted and means "nothing to do"
/// (writing 0 to a node word clears it). `id` is the command id the
/// server invents, usually `modbus-<counter>`.
pub fn command_from_holding(addr: u16, value: u16, id: &str) -> Result<Option<Command>, MapError> {
    match addr {
        0..=7 => {
            let node = (addr + 1) as NodeId;
            let kind = match value {
                cmd_word::NONE => return Ok(None),
                cmd_word::ON => ActionKind::On,
                cmd_word::OFF => ActionKind::Off,
                cmd_word::FORCE_OFF => ActionKind::ForceOff,
                cmd_word::RESET => ActionKind::Reset,
                cmd_word::CYCLE => ActionKind::Cycle,
                _ => return Err(MapError::BadValue { addr, value }),
            };
            Ok(Some(
                Command::new(id, CommandKind::of_action(kind)).with_target(Target::Node(node)),
            ))
        }
        8 => match value {
            0 => Ok(None),
            1 => Ok(Some(
                Command::new(id, CommandKind::OnAll).with_target(Target::All),
            )),
            _ => Err(MapError::BadValue { addr, value }),
        },
        9 => Err(MapError::BadValue { addr, value }),
        _ => Err(MapError::UnknownRegister {
            kind: RegKind::HoldingRegister,
            addr,
        }),
    }
}

/// Turn a coil write into a command: 1 = `on`, 0 = `off`.
pub fn command_from_coil(addr: u16, on: bool, id: &str) -> Result<Option<Command>, MapError> {
    if addr as usize >= COIL_COUNT {
        return Err(MapError::UnknownRegister {
            kind: RegKind::Coil,
            addr,
        });
    }
    let node = (addr + 1) as NodeId;
    let kind = if on { ActionKind::On } else { ActionKind::Off };
    Ok(Some(
        Command::new(id, CommandKind::of_action(kind)).with_target(Target::Node(node)),
    ))
}

/// Default args a Modbus-born command carries: none. Modbus has no room
/// for `force`, so an `Unknown` node is refused exactly as it would be
/// over MQTT.
pub fn modbus_args() -> Args {
    Args::default()
}

/// Render the map as the Markdown document `firmware/docs/modbus_map.md`.
pub fn render_markdown() -> String {
    let mut s = String::new();
    s.push_str("# Granite controller Modbus map\n\n");
    s.push_str(&format!("Map version: {MAP_VERSION}\n\n"));
    s.push_str(
        "Generated from `granite-core/src/modbus_map.rs` (`render_markdown`). \
Do not edit by hand. Unit id and port are configuration (`sec.modbus`); \
the server is off by default and requires an allow-list.\n\n",
    );
    for kind in [
        RegKind::DiscreteInput,
        RegKind::InputRegister,
        RegKind::HoldingRegister,
        RegKind::Coil,
    ] {
        s.push_str(&format!("## {}\n\n", kind.as_str()));
        s.push_str("| Address | Name | Meaning | Scale | Access |\n");
        s.push_str("|---|---|---|---|---|\n");
        for e in MAP.iter().filter(|e| e.kind == kind) {
            s.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                e.addr,
                e.name,
                e.meaning,
                e.scale,
                e.access.as_str()
            ));
        }
        s.push('\n');
    }
    s.push_str("## Fault flags (input register 13)\n\n");
    s.push_str("| Bit | Meaning |\n|---|---|\n");
    for (bit, meaning) in [
        (
            fault_bits::EXPANDER,
            "expander readback mismatch or press deadline",
        ),
        (fault_bits::SENSE, "power LEDs unreadable"),
        (
            fault_bits::PROBE_MISSING,
            "a configured probe did not answer",
        ),
        (fault_bits::VIN, "bus voltage outside its window"),
        (
            fault_bits::OTA_PENDING,
            "an OTA image is pending validation",
        ),
        (
            fault_bits::CONFIG_FALLBACK,
            "a config section fell back to defaults",
        ),
        (fault_bits::MQTT_DOWN, "broker configured but not connected"),
    ] {
        s.push_str(&format!("| {} | {} |\n", bit.trailing_zeros(), meaning));
    }
    s.push('\n');
    s.push_str(
        "Writes to a node command word or a coil become the same `Command` \
the MQTT and HTTP paths use, so the refusal rules are identical: an action \
on a node whose state is `unknown` is refused, because Modbus cannot carry \
`force`.\n",
    );
    s
}

/// The map version as a string, for the documentation header and `/id`.
pub fn map_version_string() -> String {
    MAP_VERSION.to_string()
}
